### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/ElasticQuery#18]

**Comment by FelixSchwarz** [comment]
would you mind expanding a bit on this? Is Python 3 currently not supported? Any hint what needs to be done here? (Also a travis build instance would be nice to have btw)

**Comment by Fizzadar** [comment]
Sorry I never got back to you @FelixSchwarz! Yeah I meant Python 3 support which is now out :)

Closed @ https://github.com/Fizzadar/ElasticQuery/commit/114fedb8c67b760d4ed624201c86510887d0a80f

**Comment by FelixSchwarz** [comment]
> Yeah I meant Python 3 support which is now out :)

Thanks for that :-)
