### ISSUE TITLE
why remove filter item in new version

### ISSUE THREAD

**Issue by litao3rd** [Fizzadar/ElasticQuery#21]
Hi, I noticed that there is a filter object in old version of ElasticQuery, why did you remove it in new version of the source code? Thx for your sharing

**Comment by Fizzadar** [comment]
Hi @litao3rd! I removed it as filter queries have been deprecated in favor of bool queries (https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-filtered-query.html).

v2 of the package supports it for older ES versions :)
