### ISSUE TITLE
Support for range aggregation

### ISSUE THREAD

**Issue by amribr** [Fizzadar/ElasticQuery#3]
I am using ElasticQuery and I needed to add support for [range aggregation](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html).

I think it would be great if the library can support range aggregations.

**Comment by Fizzadar** [comment]
I've added this in @ https://github.com/Fizzadar/ElasticQuery/commit/24144cb6997b6ce7a7c3463ce27324edc806bd5e, released as v1.5 :)
