### ISSUE TITLE
Adding "boosting" query type 

### ISSUE THREAD

**Issue by patilvikram** [Fizzadar/ElasticQuery#6]
Adding type of boosting query type so client can make queries with custom boosts.

**Comment by Fizzadar** [comment]
@patilvikram sorry it took so long, but this can now be achieved in ElasticQuery v2.0.1 which I just released. This includes the boost query type (https://github.com/Fizzadar/ElasticQuery/blob/develop/docs/queries.md#boost) as well as being able to pass `boost=True` to other Query objects which support it.
